### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by allgreed** [yasiupl/rocket.watch#12]
Please add LICENSE so that people can contribute freely knowing on which license their work will be published.

I personally recommend (in order of preference for this project):
- Some GPL flavour (in order to go full Stallman :D)
- WTFPL (confuses the hell out of those corporate lawyers xD)
- MIT (industry standard)

**Comment by yasiupl** [comment]
I'm not sure what to choose. I would like the project to be as open source as possible, while restricting the ability of 3rd parties to monetize the source code. Considering it is a full fledged website code that can be modified and deployed with ads very easily, someone could leech money off it, and that's not something I'm comfortable with.

**Comment by allgreed** [comment]
@yasiupl You may be interested in BSD-n-clause. If you get the n right than (I guess 3) it's permissive, yet prevents people from using your brand. So someone could make another version, but he/she won't be allow to call it rocket.watch and since the brand is all over the place one would have to modify it (which is additional effort) to remove the brand. Here's an [excellent Quora thread](https://www.quora.com/What-is-the-best-free-for-non-commercial-use-license-to-use-for-an-open-source-project) if you'd like to gain some knowledge yourself.

Furthermore I think that protecting your code from commercial usage isn't worth it. For someone to deploy the adds you'll need to have enough technical knowledge to make money somewhere else and rocket watchers are a very small crowd, you'd have to convince them to go to another site - this isn't easy and requires additional effort.

**Comment by CAM-Gerlach** [comment]
@yasiupl FYI, you'll need a license before people can contribute, otherwise you won't legally be able to use their code (or at least you're in a pretty hazy legal gray area), they won't be able to use yours and you won't be able to relicense their contributions to whatever license you choose later unless you can get every contributor to agree in writing to do so under your chosen license. Currently, that just means @allgreed but if others start contributing then the problem expands exponentially since if even one person doesn't agree (or you can't get in touch with them), you have to strip out anything they contributed and redo it or you can't legally relicense at all. Speaking from experience its so much easier to do this ASAP.

IMO, BSD is a poorly written license that should be avoided if possible due to the legally erroneous and unnecessary "All rights reserved" clause, and even the 3 clause doesn't do very much more to protect you in the regard you want, nor is it designed to, since they already can't use your brand commercially in a way that might cause confusion (i.e. by offering any similar service) due to trademark law, and they can't use your domain name due to you owning it. Furthermore, this offers virtually no protection for the code itself (that's why its called a "permissive" license).

While you can't straight-up restrict commercial use or redistribution entirely with a FOSS license or else it wouldn't be FOSS at all (its in the FOSS definition), the strongest protection you can get and probably the closest thing to what you desire is the GNU AGPLv3. In addition to the strong copyleft, Tvioization and patent protections of the GNU GPLv3 requiring anyone distributing the code to release the source of any changes and derivative works (e.g. any other parts of a website built with code from Rocket Watch) under the same license back to you, the AGPL extends this to code hosted on remote servers that users interact with (i.e. a website just like RocketWatch), so even if the code is only server side, they still must release the code and any changes, improvements and other content used on the site (potentially including other parts of the site if it was more than just a simple clone) publicly and license it back to you. You could also license any graphic assets under a different, GPL compatible license (e.g. CC-BY-SA 4.0) which would require anyone using them to state rocket watch was the source and link back to you.

While this means they can still deploy the site itself, they would need to have both the money and know how to find the code, build the site, deploy it, add the ad frameworks, configure a domain, do the work to promote it and get the word out there, and continue maintaining it all without leveraging your existing name recognition, branding, community or support, and if they do try to add anything that makes people want to use their site over the more well known alternative, those improvements would have to get released right back to you improving rocket watch in turn, so they would never have the chance to grow the site into something that truly went beyond the original (without benefitting the original too). Furthermore they would not have the revenue stream from Patreon to rely upon as you do, just ad money (which itself requires a large audience which they would have to spend time and money building, which would defeat the point of making money to begin with).

Ultimately, you have to weigh the chance of this happening times the relatively few viewers it would likely peel off vs. the benefits of the community using, contributing to and wanting to support Rocket Watch as an open source project. I'd think that's a worthy tradeoff, considering what you've built with Rocket Watch is much more than just a site—its a community.

**Comment by CAM-Gerlach** [comment]
Otherwise if you're not going to go AGPL, GPL doesn't offer you real protection except for the user side code and the more wishy-washy weak-copyleft licenses are stuck between providing useful protection and the flexibility of a permissive license so I'd just go with MIT otherwise, like @allgreed said its the standard and for a good reason--its simple, legally solid, widely used and compatible with the ecosystem.

**Comment by yasiupl** [comment]
Great insight @CAM-Gerlach, thank you. Choosing a license should probably be a higher up my list of priorities, but It just felt like "bike-shedding" given the temporary lack of my focus on the project. On the other hand I didn't want to choose whatever and then backpedal if something goes wrong in the future. 

AGPL sounds really good, but If you think It might scare off potential FOSS contributors I might want to choose something more permissive. After all, the only thing of value is the name of the project ( the domain) and the community aspect, which cannot be simply copied. 

I would like to hear what @allgreed  thinks about it.

**Comment by CAM-Gerlach** [comment]
I'm not sure AGPLv3 would scare off any contributors, its not a CLA or anything so people still own the rights to their own work just like they would with a permissive license, so it doesn't change anything there. Unless they are weird and esoteric, I've never really known licenses to scare off contributors, unlike CLAs, with a notable exception of having no license at all (I and many others I know would and could not contribute to a no-license repo). However, it could "scare off" some people who may want to re-use your work for good or ill but don't want to take the time to respect your wishes and comply with the license terms, which is probably a net positive. It does mean you have to think about GPL compatibility, though in this day and age pretty much everything is at least with v3 so I don't think that would be an issue.

But yeah, not only should we get @allgreed 's opinion but he is _required_ to agree to any such relicensing unless you want to nuke all his code from the repo. In fact, as it stands you don't technically have explicit permission to use his work at all unless you have a written agreement between you two (in the US you could probably argue an implied or oral contract but that would probably be a shaky defense in a civil law jurisdiction like Poland). That is exactly why a license, _any_ license, should be decided upon ASAP following his agreement to avoid any issues over this. The longer you kick this down the road instead of deciding on something and sticking with it, the more people you've have to bikeshed with over the license down the road, and you won't be able to make a decision until every one of them agree.

**Comment by yasiupl** [comment]
Confirmed with @allgreed  in person. Fell free to reopen if there are any objections.

**Comment by CAM-Gerlach** [comment]
Thanks @yasiupl !
