### ISSUE TITLE
Card sizing unification

### ISSUE THREAD

**Issue by Qballla** [yasiupl/rocket.watch#3]
![projectgitbug](https://user-images.githubusercontent.com/39501274/47255934-1d726380-d478-11e8-9fab-1921555ac560.jpg)

Size of card is not the same for each element. While the content needs more lines it is heigher than other card elements.

**Comment by yasiupl** [comment]
Thanks for opening this issue. I will look into how I can change the design to take this case into account.

**Comment by CAM-Gerlach** [comment]
On the Lektor theme framework I built that has that has a card layout I just cooked up some hacky Javascript that checks the height of the other cards in the row and sets each card to the max size on page load and when the viewport size changes, but being an absolute novice at web stuff (particularly at the time I did that) I'm sure there must be a better way; this must be a common problem.

**Comment by yasiupl** [comment]
My lack of fix for this yet is because it happens so rarely, probably only for Vandenberg AFB + SpaceX launches which is a really long string combination. Your Js fix sounds pretty straight forward, but I think css flex fixes a similar problem. 

I will try to break it, and fix it when I have some time.
